/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly Full 26.1.2.Final (WildFly Core 18.1.2.Final) - 2.2.19.Final
 * Generated at: 2023-10-11 08:23:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Лаб. 2</title>\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./media/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/main.css\">\n");
      out.write("</head>\n");
      out.write("<body class=\"barbie-mode\">\n");
      out.write("<h2 class=\"header\" id=\"student-info\">\n");
      out.write("    Балин Артем Алексеевич P3212, вариант №2249\n");
      out.write("</h2>\n");
      out.write("<p class=\"mode\" onclick=\"pic(1)\" id=\"barbie-mode\">Barbie mode on</p>\n");
      out.write("<p class=\"mode covered\" onclick=\"pic(2)\" id=\"openheimer-mode\">\n");
      out.write("    Oppenheimer mode on\n");
      out.write("</p>\n");
      out.write("<div class=\"main-container\">\n");
      out.write("    <div class=\"form_container\">\n");
      out.write("        <form class=\"input-form\">\n");
      out.write("            <p>\n");
      out.write("                <svg xmlns=\"http://www.w3.org/2000/svg\" id=\"svg\">\n");
      out.write("                    <line\n");
      out.write("                            x1=\"0\"\n");
      out.write("                            y1=\"150\"\n");
      out.write("                            x2=\"300\"\n");
      out.write("                            y2=\"150\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"150\"\n");
      out.write("                            y1=\"0\"\n");
      out.write("                            x2=\"150\"\n");
      out.write("                            y2=\"300\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <polygon points=\"300,150 295,155 295, 145\" fill=\"#000720\" stroke=\"#000720\"></polygon>\n");
      out.write("                    <polygon points=\"150,0 145,5 155,5\" fill=\"#000720\" stroke=\"#000720\"></polygon>\n");
      out.write("                    <text x=\"282\" y=\"170\">x</text>\n");
      out.write("                    <text x=\"163\" y=\"14\">y</text>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"270\"\n");
      out.write("                            y1=\"148\"\n");
      out.write("                            x2=\"270\"\n");
      out.write("                            y2=\"152\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <text x=\"265\" y=\"140\">\n");
      out.write("                        <tspan class=\"graph_value\">R</tspan>\n");
      out.write("                    </text>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"210\"\n");
      out.write("                            y1=\"148\"\n");
      out.write("                            x2=\"210\"\n");
      out.write("                            y2=\"152\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <text x=\"200\" y=\"140\">\n");
      out.write("                        <tspan class=\"graph_value\">R</tspan>\n");
      out.write("                        /2\n");
      out.write("                    </text>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"90\"\n");
      out.write("                            y1=\"148\"\n");
      out.write("                            x2=\"90\"\n");
      out.write("                            y2=\"152\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <text x=\"75\" y=\"140\">\n");
      out.write("                        -\n");
      out.write("                        <tspan class=\"graph_value\">R</tspan>\n");
      out.write("                        /2\n");
      out.write("                    </text>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"30\"\n");
      out.write("                            y1=\"148\"\n");
      out.write("                            x2=\"30\"\n");
      out.write("                            y2=\"152\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <text x=\"20\" y=\"140\">\n");
      out.write("                        -\n");
      out.write("                        <tspan class=\"graph_value\">R</tspan>\n");
      out.write("                    </text>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"148\"\n");
      out.write("                            y1=\"30\"\n");
      out.write("                            x2=\"152\"\n");
      out.write("                            y2=\"30\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <text x=\"156\" y=\"35\">\n");
      out.write("                        <tspan class=\"graph_value\">R</tspan>\n");
      out.write("                    </text>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"148\"\n");
      out.write("                            y1=\"90\"\n");
      out.write("                            x2=\"152\"\n");
      out.write("                            y2=\"90\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <text x=\"156\" y=\"95\">\n");
      out.write("                        <tspan class=\"graph_value\">R</tspan>\n");
      out.write("                        /2\n");
      out.write("                    </text>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"148\"\n");
      out.write("                            y1=\"210\"\n");
      out.write("                            x2=\"152\"\n");
      out.write("                            y2=\"210\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <text x=\"156\" y=\"215\">\n");
      out.write("                        -\n");
      out.write("                        <tspan class=\"graph_value\">R</tspan>\n");
      out.write("                        /2\n");
      out.write("                    </text>\n");
      out.write("                    <line\n");
      out.write("                            x1=\"148\"\n");
      out.write("                            y1=\"270\"\n");
      out.write("                            x2=\"152\"\n");
      out.write("                            y2=\"270\"\n");
      out.write("                            stroke=\"#000720\"\n");
      out.write("                    ></line>\n");
      out.write("                    <text x=\"156\" y=\"275\">\n");
      out.write("                        -\n");
      out.write("                        <tspan class=\"graph_value\">R</tspan>\n");
      out.write("                    </text>\n");
      out.write("                    <polygon points=\"300,150 295,155 295, 145\" fill=\"#000720\" stroke=\"#000720\"></polygon>\n");
      out.write("                    <polygon points=\"150,0 145,5 155,5\" fill=\"#000720\" stroke=\"#000720\"></polygon>\n");
      out.write("                    <rect\n");
      out.write("                            x=\"150\"\n");
      out.write("                            y=\"150\"\n");
      out.write("                            width=\"120\"\n");
      out.write("                            height=\"120\"\n");
      out.write("                            fill-opacity=\"0.4\"\n");
      out.write("                            stroke=\"navy\"\n");
      out.write("                            fill=\"blue\"\n");
      out.write("                    ></rect>\n");
      out.write("                    <polygon\n");
      out.write("                            points=\"31,150 150,150 150, 90\"\n");
      out.write("                            fill-opacity=\"0.4\"\n");
      out.write("                            stroke=\"navy\"\n");
      out.write("                            fill=\"blue\"\n");
      out.write("                    ></polygon>\n");
      out.write("                    <path\n");
      out.write("                            d=\"M150 150 L150 90 A60 60 0 0 1 210 150 Z\"\n");
      out.write("                            fill-opacity=\"0.4\"\n");
      out.write("                            stroke=\"navy\"\n");
      out.write("                            fill=\"blue\"\n");
      out.write("                    ></path>\n");
      out.write("                </svg>\n");
      out.write("            </p>\n");
      out.write("            <div class=\"input-argument-container\">\n");
      out.write("                <label class=\"input-argument\">X:</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X-2\"\n");
      out.write("                        id=\"X-2\"\n");
      out.write("                        onchange=\"uncheckboxes('-2')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X-2\">-2</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X-1.5\"\n");
      out.write("                        id=\"X-1.5\"\n");
      out.write("                        onchange=\"uncheckboxes('-1.5')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X-1.5\">-1.5</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X-1\"\n");
      out.write("                        id=\"X-1\"\n");
      out.write("                        onchange=\"uncheckboxes('-1')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X-1\">-1</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X-0.5\"\n");
      out.write("                        id=\"X-0.5\"\n");
      out.write("                        onchange=\"uncheckboxes('-0.5')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X-0.5\">-0.5</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X-0\"\n");
      out.write("                        id=\"X-0\"\n");
      out.write("                        onchange=\"uncheckboxes('-0')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X-0\">0</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X+0.5\"\n");
      out.write("                        id=\"X+0.5\"\n");
      out.write("                        onchange=\"uncheckboxes('+0.5')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X+0.5\">0.5</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X+1\"\n");
      out.write("                        id=\"X+1\"\n");
      out.write("                        onchange=\"uncheckboxes('+1')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X+1\">1</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X+1.5\"\n");
      out.write("                        id=\"X+1.5\"\n");
      out.write("                        onchange=\"uncheckboxes('+1.5')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X+1.5\">1.5</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"checkbox\"\n");
      out.write("                        name=\"X+2\"\n");
      out.write("                        id=\"X+2\"\n");
      out.write("                        onchange=\"uncheckboxes('+2')\"\n");
      out.write("                        class=\"input-checkbox\"\n");
      out.write("                >\n");
      out.write("                <label for=\"X+2\">2</label>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"input-argument-container\">\n");
      out.write("                <label class=\"input-argument\" for=\"Y-input\">Y:</label>\n");
      out.write("                <input\n");
      out.write("                        type=\"text\"\n");
      out.write("\n");
      out.write("                        class=\"text-input\"\n");
      out.write("                        name=\"Y\"\n");
      out.write("                        placeholder=\"Y: (-3...3)\"\n");
      out.write("                        id=\"Y-input\"\n");
      out.write("                >\n");
      out.write("            </div>\n");
      out.write("            <div class=\"input-argument-container\">\n");
      out.write("                <label class=\"input-argument\">R:</label>\n");
      out.write("                <label>\n");
      out.write("                    <input class=\"input-radio\" type=\"radio\" name=\"radius\" value=\"1\">\n");
      out.write("                    1\n");
      out.write("                </label>\n");
      out.write("                <label>\n");
      out.write("                    <input class=\"input-radio\" type=\"radio\" name=\"radius\" value=\"1.5\">\n");
      out.write("                    1.5\n");
      out.write("                </label>\n");
      out.write("                <label>\n");
      out.write("                    <input class=\"input-radio\" type=\"radio\" name=\"radius\" value=\"2\">\n");
      out.write("                    2\n");
      out.write("                </label>\n");
      out.write("                <label>\n");
      out.write("                    <input class=\"input-radio\" type=\"radio\" name=\"radius\" value=\"2.5\">\n");
      out.write("                    2.5\n");
      out.write("                </label>\n");
      out.write("                <label>\n");
      out.write("                    <input class=\"input-radio\" type=\"radio\" name=\"radius\" value=\"3\">\n");
      out.write("                    3\n");
      out.write("                </label>\n");
      out.write("            </div>\n");
      out.write("            <input\n");
      out.write("                    type=\"submit\"\n");
      out.write("                    value=\"Send it!\"\n");
      out.write("                    id=\"form-button\"\n");
      out.write("            >\n");
      out.write("        </form>\n");
      out.write("        <p id=\"error-logs\"></p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"table-container\">\n");
      out.write("        <table id=\"table-results\">\n");
      out.write("            <tr>\n");
      out.write("                <th class=\"argument-column\">X</th>\n");
      out.write("                <th class=\"argument-column\">Y</th>\n");
      out.write("                <th class=\"argument-column\">R</th>\n");
      out.write("                <th class=\"result-column\">Result</th>\n");
      out.write("                <th class=\"time-column\">In work, ms</th>\n");
      out.write("                <th class=\"time-column\">Received at</th>\n");
      out.write("            </tr>\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("<script src=\"./js/client.js\"></script>\n");
      out.write("<script src=\"./js/formAction.js\"></script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /index.jsp(282,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/index.jsp(282,12) '${Points}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${Points}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /index.jsp(282,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fforEach_005f0.setVar("point");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <tr>\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.split(' ')[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.split(' ')[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.split(' ')[2]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.split(' ')[3]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.split(' ')[4]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                    <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${point.split(' ')[5]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                </tr>\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
